### ISSUE TITLE
Unexpected token '?'

### ISSUE THREAD

**Issue by Ferratzo** [Androz2091/discord-player#100]
**Hi, When I try to run the discord bot (I'll insert the code)**

```

const Discord = require("discord.js")
const bot = new Discord.Client();

settings = {
    prefix: ",",
    token: "(My token)"
};
/////////////Mensaje Funcionalidad///////////
bot.on("ready", bot  => {
    console.log("Listo!");
})
////////////Música/////////////////////////
const { Player } = require("discord-player");
const player = new Player(bot);
bot.player = player;

bot.on("message" , async message => {

    const args = message.content.slice(settings.prefix.length).trim().split(/ +/g);
    const command = args.shift().toLowerCase();

    if (command === "play", "p"){
        let track = await bot.player.play(message.member.voice.channel, args[0], message.member.user.tag);
        message.channel.send(`Reproduciendo ${track.name}! - Pedida por ${track.requestedBy}`);
    }

    if (command === "stop", "st"){
        let track = await bot.player.stop(message.guild.id);
        message.channel.send(`Detenida`);
    }
});

bot.login(settings.token);

```
**I get this SyntaxError, but when I look into the line which is supposedly wrong, I don't see any problem**

`      }, this.options.leaveOnEmptyCooldown ?? 0)
                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Documentos HDD\Discord bots\bot1\node_modules\discord-player\index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)`

**I wish you could help me, because I'm an absolutely newbie at this thing. Thanks for your time**

**Comment by atulya2109** [comment]
Update Node JS to the current release

**Comment by Ferratzo** [comment]
WOW, I'm dumb, thanks for your help. xD
