### ISSUE TITLE
client.player.on not a function

### ISSUE THREAD

**Issue by Cyanitem** [Androz2091/discord-player#104]
const player = new Player(client, { 
    leaveOnEmpty: true, 
    leaveOnEnd: true, 
    leaveOnStop: true 
});

Object.keys(customFilters).forEach(c => {
    player.filters[`${c}`] = customFilters[c];
});

client.player = player;
client.player.on('error', (message, error) => {
              ^

TypeError: client.player.on is not a function
    at Object.<anonymous> (/home/runner/MusicBoat/index.js:73:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! Test failed.  See above for more details.

**Comment by Androz2091** [comment]
Fixed in v3.0.0
