### ISSUE TITLE
Unexpected token '?' while starting bot causing it to crash

### ISSUE THREAD

**Issue by Spongeyboi** [Androz2091/discord-player#107]
```
[redacted]\node_modules\discord-player\src\Player.js:608
        }, this.options.leaveOnEmptyCooldown ?? 0)
                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Drawi\Documents\Discord\Bot\MusicalBeta\node_modules\discord-player\index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

welp. I have no idea what to do.

**Comment by MrPerfectShot** [comment]
You need to update your node.js to v14

**Comment by Spongeyboi** [comment]
ok

**Comment by aaiiddaann** [comment]
Might want to pin this... I've seen multiples of this issue here, (and I was about to make another.) :p
