### ISSUE TITLE
}, this.options.leaveOnEmptyCooldown ?? 0)

### ISSUE THREAD

**Issue by HashedDev** [Androz2091/discord-player#112]
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (F:\Discord Bot Controls\node_modules\discord-player\index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by MrPerfectShot** [comment]
Hello update your node to v14

**Comment by HashedDev** [comment]
I've updated it and it works fine. Also v3 sucks use v2
