### ISSUE TITLE
Error: No tracks found for the specified query.

### ISSUE THREAD

**Issue by FredTheNoob** [Androz2091/discord-player#122]
Full error:

```js
(node:10284) UnhandledPromiseRejectionWarning: Error: No tracks found for the specified query.
    at /home/fred/Wavynn/node_modules/discord-player/src/Player.js:175:44
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Snowflake107** [comment]
ytsr is broken. Please wait until a patch is published!

**Comment by FredTheNoob** [comment]
Will do, thank you for the update!

**Comment by inhydrox** [comment]
YouTube updated something in their search results I use lavalink so it's already fixed in that and I heard some packages got takedown

**Comment by inhydrox** [comment]
I guess this might help you [scraper](https://github.com/HermanFassett/youtube-scrape/blob/master/scraper.js)

**Comment by FredTheNoob** [comment]
Thank you for this @inhydrox. Highly appreciated! :]

**Comment by inhydrox** [comment]
👍

**Comment by Androz2091** [comment]
Fixed. Install v3.0.0
