### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by YuriXbr** [Androz2091/discord-player#1244]
```
\Bot\Music-bot-master\node_modules\discord-player\dist\Player.js:388
author: (_d = (_c = m.track.artists[0]) === null || _c === void 0 ? void 0 : _c.name) !== null && _d !== void 0 ? _d : "Unknown Artist",
                                                                   ^
TypeError: Cannot read properties of undefined (reading '0')
    at \Bot\Music-bot-master\node_modules\discord-player\dist\Player.js:388:68
    at Array.map (<anonymous>)
    at Player.<anonymous> (\Bot\Music-bot-master\node_modules\discord-player\dist\Player.js:383:72)
    at Generator.next (<anonymous>)
    at fulfilled (\Bot\Music-bot-master\node_modules\tslib\tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**
????

**Expected behavior**
the song requested by the play command through the spotify link starts playing

**Please complete the following information:**
 - Node Version: 17.1.0
 - Discord Player Version: ^5.2.2
 - Discord.js Version: ^13.6.0

**Comment by DevAndromeda** [comment]
try v5.3.x, re-open if this still persists
