### ISSUE TITLE
TypeError: discord_js_1.IntentsBitField is not a constructor

### ISSUE THREAD

**Issue by YuriXbr** [Androz2091/discord-player#1312]
**Describe the bug**
Error on startup

**ERROR**
```
C:\Users\claud\Desktop\.node\Bot\Music-bot-master\node_modules\discord-player\dist\Player.js:46
        if (this.client?.options?.intents && !new discord_js_1.IntentsBitField(this.client?.options?.intents).has(discord_js_1.IntentsBitField.Flags.GuildVoiceStates)) {
                                              ^

TypeError: discord_js_1.IntentsBitField is not a constructor
    at new Player (C:\Users\claud\Desktop\.node\Bot\Music-bot-master\node_modules\discord-player\dist\Player.js:46:47)
    at Object.<anonymous> (C:\Users\claud\Desktop\.node\Bot\Music-bot-master\main.js:21:17)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Please complete the following information:**
 - Node Version: 17.1.0
 - Discord Player Version: 5.3.1
 - Discord.js Version: 13.6.0

**Comment by lan7ium** [comment]
I have exactly the same problem but I am in a different version of node => 


    Node Version: 16.15.0
    Discord Player Version: 5.1.0
    Discord.js Version: 13.1.0
    
   As I want to stay on V13 of Discord.js for the moment I prefer to stay on 5.1.0 of your framework.

**Comment by DevAndromeda** [comment]
Use discord.js v14
