### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by securing-ab** [Androz2091/discord-player#1376]
**Describe the bug**
`[Spike test] Error emitted from the queue occured on Spike Canary: Command failed: 
 [antiCrash] => Uncaught Exception/Catch (MONITOR)
TypeError: cb is not a function
    at FFmpeg.kill (C:\Users\user\Documents\GitHub\spike\node_modules\duplex-child-process\index.js:145:11)
    at Object.destroyer (node:internal/streams/destroy:317:59)
    at node:internal/streams/pipeline:80:17
    at finishImpl (node:internal/streams/pipeline:216:23)
    at finish (node:internal/streams/pipeline:203:5)
    at node:internal/streams/pipeline:242:13
    at node:internal/util:445:5
    at FFmpeg.<anonymous> (node:internal/streams/pipeline:73:7)
    at FFmpeg.<anonymous> (node:internal/util:445:5)
    at FFmpeg.onerror (node:internal/streams/end-of-stream:133:14) uncaughtException
 [antiCrash] => Uncaught Exception/Catch
TypeError: cb is not a function
    at FFmpeg.kill (C:\Users\user\Documents\GitHub\spike\node_modules\duplex-child-process\index.js:145:11)
    at Object.destroyer (node:internal/streams/destroy:317:59)
    at node:internal/streams/pipeline:80:17
    at finishImpl (node:internal/streams/pipeline:216:23)
    at finish (node:internal/streams/pipeline:203:5)
    at node:internal/streams/pipeline:242:13
    at node:internal/util:445:5
    at FFmpeg.<anonymous> (node:internal/streams/pipeline:73:7)
    at FFmpeg.<anonymous> (node:internal/util:445:5)
    at FFmpeg.onerror (node:internal/streams/end-of-stream:133:14) uncaughtException`
**Expected behavior**

Play the song.

**
 - Node Version: v16.17.0
 - Discord Player Version: latest
 - Discord.js Version: 14.4.0
**Code**
```js
/* eslint-disable no-undef */
/* eslint-disable no-unused-vars */
const { Song, Playlist } = require('spike-player')
const {QueryType} = require('discord-player')
const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js')
const { isPlaylist } = require('../utils/player')
const { postQueue } = require('../utils/postQueue')
const dl = require('play-dl')
module.exports = {
  data: new SlashCommandBuilder()
    .setName('play')
    .setDescription('Plays audio in a channel!')
    .addStringOption(option =>
      option
        .setName('query')
        .setDescription('The song or playlist that will play in the voice channel')
        .setRequired(true)
    ),
  async execute(client, interaction, discord, guildQueue) {
    try {
      /* This will get the song that has been provided */
      const query = interaction.options.getString('query')
      const channel = interaction.member.voice.channel
      if (!channel) {
        interaction.reply({
          content: 'You must be in a voice channel to use this command!',
          ephemeral: true
        })
      } else if (!interaction.guild.members.me.permissions.has(PermissionFlagsBits.Connect)) {
        interaction.reply('I am sorry but I do not have the permissions to connect to the voice channel')
      } else if (!interaction.guild.members.me.permissions.has(PermissionFlagsBits.Speak)) {
        interaction.reply('I am sorry but I do not have the permissions to speak in the voice channel')
      } else if (interaction.guild.members.me.voice.channel && channel !== interaction.guild.members.me.voice.channel)
        return interaction.reply({
          content: `You must be in the same voice channel as me to use this command!`,
          ephemeral: true
        })
        const {getVoiceConnection} = require('@discordjs/voice')
        let connection = getVoiceConnection(interaction.guild.id)
        if(connection){
          connection.destroy()
        }
      let player = client.player
      interaction.deferReply
      if (!interaction.member.voice.channelId) return await interaction.reply({ content: "You are not in a voice channel!", ephemeral: true });
      if (interaction.guild.members.me.voice.channelId && interaction.member.voice.channelId !== interaction.guild.members.me.voice.channelId) return await interaction.reply({ content: "You are not in my voice channel!", ephemeral: true });
      const queue = player.createQueue(interaction.guild, {
          metadata: {
              channel: interaction.channel
          }
      });
      
      // verify vc connection
      try {
          if (!queue.connection) await queue.connect(interaction.member.voice.channel);
      } catch {
          queue.destroy();
          return await interaction.reply({ content: "Could not join your voice channel!", ephemeral: true });
      }

      await interaction.deferReply();
      const track = await player.search(query, {
          requestedBy: interaction.user
      }).then(x => x.tracks[0]);
      if (!track) return await interaction.followUp({ content: `❌ | Track **${query}** not found!` });
      queue.play(track);

      return await interaction.followUp({ content: `⏱️ | Loading track **${track.title}**!` });
    /*queue.setData({
        initMessage: interaction.channel
      })*/
      //let song = new Song(track, queue)

      /*define song var for embed
      let name = song.name
      let url = song.url
      let author = song.author
      let duration = song.duration
      let thing = new EmbedBuilder()
        .setTitle('<a:record:838860186151026748> Now Playing:')
        .setThumbnail(song.thumbnail)
        .setColor('Random')
        .setDescription(`Song - **[${name}](${url}})**\nAuthor - **${author}**\nDuration - **${duration}**\n\n`)
        .setTimestamp()
        .setFooter({
          text: `Added By ${interaction.user.username}#${interaction.user.discriminator}`
        })*/
    }catch (error) {
      console.log(error)
  }
    }
}
```

**Comment by securing-ab** [comment]
ffmpeg is installed (ffmpeg-static) and all the other reqs

**Comment by securing-ab** [comment]
@Androz2091

**Comment by milkbag19** [comment]
Any updates to this?
