### ISSUE TITLE
Playing Spotify Album URL not working (v5.4.0)

### ISSUE THREAD

**Issue by ervin-sungkono** [Androz2091/discord-player#1535]
I'm getting this error when i enter a spotify album url to the query using /play command

```sh
TypeError: Cannot read properties of undefined (reading '0')
    at Player.search (/home/container/node_modules/discord-player/dist/Player.js:416:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (/home/container/commands/play.js:22:24)
```

1. Use /play command
2. Enter a spotify album url, example: https://open.spotify.com/album/3264OQjRrLfFWnEWdcfCSC and https://open.spotify.com/album/0dVmEBpjqyfXPYs0Xyy4BJ

**Expected behavior**
The discord bot should be able to play from album, however it throws a not found result instead

**Screenshots**
![image](https://user-images.githubusercontent.com/43065067/214771894-f988acee-ca98-4ddd-ab95-b4cdc2558922.png)

**Please complete the following information:**
 - Node Version: 16.17.1
 - Discord Player Version: 5.4.0
 - Discord.js Version: 14.7.1

**Additional context**
I was able to fix the issue by changing line 416:417 at Player.js from:
```js
name: spotifyPlaylist.artists[0]?.name ?? "Unknown Artist",
url: spotifyPlaylist.artists[0]?.external_urls?.spotify ?? null
```
to this:
```js
name: spotifyPlaylist.artists?.[0]?.name ?? "Unknown Artist",
url: spotifyPlaylist.artists?.[0]?.external_urls?.spotify ?? null
```
However this only fixes the undefined error, doesn't fix the problem where the artist will always be "Unknown Artist". This is because the spotifyPlaylist response body doesnt actually return an artist attribute, i suggest changing artists to subtitle so that it can return the artist's name for a spotify album/playlist

I also changed line 431:442 at Player.js from this:
```js
if (spotifyPlaylist.type !== "playlist") {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    playlist.tracks = spotifyPlaylist.tracks.items.map((m) => {
            const data = new Track_1.default(this, {
              title: m.name ?? "",
              description: m.description ?? "",
              author: m.artists[0]?.name ?? "Unknown Artist",
              url: m.external_urls?.spotify ?? query,
              thumbnail: spotifyPlaylist.images[0]?.url ?? "https://www.scdn.co/i/_global/twitter_card-default.jpg",
              duration: Util_1.Util.buildTimeCode(Util_1.Util.parseMS(m.duration_ms)),
              views: 0,
              requestedBy: options.requestedBy,
              playlist,
              source: "spotify"
        });
        return data;
    });
}
```
to this:
```js
if (spotifyPlaylist.type !== "playlist") {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    playlist.tracks = spotifyPlaylist.trackList.map((m) => {
        const data = new Track_1.default(this, {
            title: m.title ?? "",
            description: m.description ?? "",
            author: m.subtitle ?? "Unknown Artist",
            url: m.external_urls?.spotify ?? query,
            thumbnail: m.album?.images?.[0]?.url ?? "https://www.scdn.co/i/_global/twitter_card-default.jpg",
            duration: Util_1.Util.buildTimeCode(Util_1.Util.parseMS(m.duration)),
            views: 0,
            requestedBy: options.requestedBy,
            playlist,
            source: "spotify"
        });
        return data;
    });
}
```
Here is an example of the spotifyPlaylist response body
```json
{
  type: 'album',
  name: 'Gurenge (Demon Slayer) [Remix]',
  uri: 'spotify:album:2hGgL92dcBNQG8jEKtac0k',
  id: '2hGgL92dcBNQG8jEKtac0k',
  title: 'Gurenge (Demon Slayer) [Remix]',
  subtitle: 'NSZX',
  coverArt: {
    extractedColors: { colorDark: [Object] },
    sources: [{
      height: 640,
      width: 640,
      url: 'https://i.scdn.co/image/ab67616d0000b2736acbb6167824a651fe60dd40'
    },
    {
      height: 300,
      width: 300,
      url: 'https://i.scdn.co/image/ab67616d00001e026acbb6167824a651fe60dd40'
    },
    {
      height: 64,
      width: 64,
      url: 'https://i.scdn.co/image/ab67616d000048516acbb6167824a651fe60dd40'
    }]
  },
  releaseDate: null,
  duration: 0,
  maxDuration: 0,
  isPlayable: true,
  isExplicit: false,
  hasVideo: false,
  relatedEntityUri: '',
  trackList: [
      uid: '5e0f96b809609b2792f1',
      title: 'Gurenge (Demon Slayer) - Remix',
      subtitle: 'NSZX',
      isExplicit: false,
      duration: 106307,
      isPlayable: true,
      audioPreview: [Object]
    }
  ]
}
```

**Comment by skdhg** [comment]
@ervin-sungkono it is already resolved in dev version, you can try it with `npm i discord-player@dev`

**Comment by ervin-sungkono** [comment]
Ah i see, thanks
