### ISSUE TITLE
Player crashed after a few minutes

### ISSUE THREAD

**Issue by Mittelblut9** [Androz2091/discord-player#1579]
**Describe the bug**

While playing a playlist / song the Player crash with the following error:
It happened after 20 minutes, but also after 4 minutes.
```cmd
10:39:11.726 FATAL Cannot read properties of null (reading 'id')
{}
TypeError: Cannot read properties of null (reading 'id')
    at Player._handleVoiceState (/app/node_modules/discord-player/dist/Player.js:108:107)
    at Client.emit (node:events:525:35)
    at VoiceStateUpdate.handle (/app/node_modules/discord.js/src/client/actions/VoiceStateUpdate.js:38:14)
    at module.exports [as VOICE_STATE_UPDATE] (/app/node_modules/discord.js/src/client/websocket/handlers/VOICE_STATE_UPDATE.js:4:35)
    at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
    at callListener (/app/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
```

**To Reproduce**

1. Queue a playlist
2. Play the playlist

**Expected behavior**

Don't crash.

**Screenshots**

_None_

**Please complete the following information:**
 - Node Version: 18.8
 - Discord Player Version: 5.4.0
 - Discord.js Version: 14.7.1

**Additional context**

_None_

**Comment by Mittelblut9** [comment]
Is there any fix planned?
