### ISSUE TITLE
TypeError: voiceChannel.join is not a function

### ISSUE THREAD

**Issue by TerThesz** [Androz2091/discord-player#163]
I got this error:
```
(node:13280) UnhandledPromiseRejectionWarning: TypeError: voiceChannel.join is not a function
    at D:\Projects\MusicBot\node_modules\discord-player\src\Player.js:258:138
    at new Promise (<anonymous>)
    at Player.play (D:\Projects\MusicBot\node_modules\discord-player\src\Player.js:254:16)
    at Client.<anonymous> (D:\Projects\MusicBot\index.js:23:41)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (D:\Projects\MusicBot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (D:\Projects\MusicBot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (D:\Projects\MusicBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (D:\Projects\MusicBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (D:\Projects\MusicBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
(node:13280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
While trying to play a song.
Code:
```javascript
const Discord = require('discord.js');
const client = new Discord.Client({ disableEveryone: true });

const {Player} = require('discord-player');
const player = new Player(client);
client.player = player;

//some boring stuff

    if (cmd === 'play') {
        let track = await client.player.play(message, "Despacito");
        message.channel.send('playin');
    }
```

**Comment by milanmdev** [comment]
I am having this error too. I think it is because of discord.js deprecating voiceChannel.join, and changing it to voice.channel.join

**Comment by Androz2091** [comment]
This is weird, `voiceChannel.join()` is never called in the Player.js file. Can you upgrade to v3.0.3 or higher?

**Comment by Androz2091** [comment]
Closed due to inactivity
