### ISSUE TITLE
Player doesn't skip unplayable track even with skipOnNoStream option enabled

### ISSUE THREAD

**Issue by pateckii** [Androz2091/discord-player#1653]
**Describe the bug**
Discord-player throws an error `Could not extract stream for this track` when playing age restricted video from YouTube.
After adding `skipOnNoStream: true` to the `nodeOptions` another error is emitted: 
`Play request received but track was not provided`

**To Reproduce**
-Play any age restricted video from YouTube, for example [https://www.youtube.com/watch?v=nwnq7o99obo](url)

**Expected behavior**

After adding `skipOnNoStream: true` discord-player should skip the unplayable song.

**Screenshots**

![image](https://user-images.githubusercontent.com/83179353/223142270-4ac48120-7b1f-4b5f-ba59-3a04fca424fd.png)
![image](https://user-images.githubusercontent.com/83179353/223142369-a278c49d-ea4c-4aa3-aae5-cbf0c3094b12.png)

**Please complete the following information:**
 - Node Version: 18.14.2
 - Discord Player Version: 6.0.0
 - Discord.js Version: 14.7.1

**Comment by pateckii** [comment]
Debug information with 'debug' event on:
```|debug| undefined
[NW] [WS] >> {"op":3,"d":1678119365040}
|debug| undefined
[NW] [WS] << {"op":6,"d":1678119365040}
|debug| undefined
[NW] [WS] >> {"op":3,"d":1678119378790}
|debug| undefined
[NW] [WS] << {"op":6,"d":1678119378790}
|debug| undefined
Received play request from guild Kielecka Ekipa (ID: 491672580512809015)
|debug| undefined
Requested option requires to play the track, initializing...
|debug| undefined
Initiating stream extraction process...
|debug| undefined
Executing onBeforeCreateStream hook (QueryType: youtubeSearch)...
|debug| undefined
Failed to get stream from onBeforeCreateStream!
|debug| undefined
Attempting to extract stream for Track { title: STARE BABY MIXTAPE CD!, url: https://www.youtube.com/watch?v=NLNw3ZZWj7c } using registered extractors
|debug| undefined
Failed to extract stream for Track { title: STARE BABY MIXTAPE CD!, url: https://www.youtube.com/watch?v=NLNw3ZZWj7c } using registered extractors
|debug| undefined
[Kielecki Basiura] Error emitted from the connection: Could not extract stream for this track
Received play request from guild Kielecka Ekipa (ID: 491672580512809015)
|debug| undefined
/home/pate/Code/basiura-dev/node_modules/discord-player/dist/index.js:929
      throw new Error("Play request received but track was not provided");
            ^

Error: Play request received but track was not provided
    at GuildQueuePlayerNode.play (/home/pate/Code/basiura-dev/node_modules/discord-player/dist/index.js:929:13)
    at GuildQueuePlayerNode.play (/home/pate/Code/basiura-dev/node_modules/discord-player/dist/index.js:954:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _Player.play (/home/pate/Code/basiura-dev/node_modules/discord-player/dist/index.js:2638:7)
    at async Client.<anonymous> (/home/pate/Code/basiura-dev/index.js:62:27)

Node.js v18.14.2```
