### ISSUE TITLE
AbortError being thrown when Player stops a queue

### ISSUE THREAD

**Issue by febkosq8** [Androz2091/discord-player#1656]
**Describe the bug**
Bot will throw a AbortError when its stops the queue, either through command or disconnection. This was supposed to be patched already keep happening mostly for me in Heroku.

Since I am handling uncaughtException in my code, my bot doesn't crash. (otherwise would have crashed the bot completely)

Attaching error stack below : 

```
AbortError: The operation was aborted
at EventTarget.abortListener (node:events:958:14)
at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
at EventTarget.dispatchEvent (node:internal/event_target:677:26)
at abortSignal (node:internal/abort_controller:308:10)
at AbortController.abort (node:internal/abort_controller:338:5)
at Timeout.<anonymous> (/app/node_modules/@discordjs/voice/dist/index.js:1931:39)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7) {
code: 'ABORT_ERR',
[cause]: DOMException [AbortError]: This operation was aborted
at new DOMException (node:internal/per_context/domexception:53:5)
at AbortController.abort (node:internal/abort_controller:336:18)
at Timeout.<anonymous> (/app/node_modules/@discordjs/voice/dist/index.js:1931:39)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
}
```

**To Reproduce**

1. Queue a playlist 
2. Stop the queue either using command or disconnect the bot
3. AbortError gets thrown

**Expected behavior**
1. Queue a playlist 
2. Stop the queue either using command or disconnect the bot
3. No error should be thrown

**Please complete the following information:**

 - Node Version: 18.14.2
 - Discord Player Version: 6.0.0
 - Discord.js Version: 14.7.1
 - @discord-player/equalizer Version: 0.2.0
 - @discord-player/extractor Version: 4.1.0
 - @discord-player/utils Version: 0.2.0
 - @discordjs/opus Version: 0.9.0
 - @discordjs/voice Version: 0.14.0

**Comment by febkosq8** [comment]
Update : Added the npm cache clean command to my Heroku procfile along with `npm start` seems to have stopped the issue. 
If I remove the cache clean then the problem seems to come back. IDK why this is the case.

```
worker: npm cache clean --force && npm start
```

**Comment by Mittelblut9** [comment]
Happenes too, when i try to add a song to the queue

**Comment by kewanfr** [comment]
I have the same error with: v6.2.0 discord-player version, djs 14.9.0 and djs/voice 0.16.0

**Comment by skdhg** [comment]
The voice connection handler was rewritten in `discord-player@dev`, please give it a try report any issues.

**Comment by febkosq8** [comment]
Tried out `discord-player@6.6.0-dev`. I still got a AbortError on kicking the bot from vc.

**Comment by febkosq8** [comment]
For me the AbortErrors used to be caught in my unhandled exception not player.events. 
Good news is that I am **no longer getting AbortErrors in the latest version - `discord-player@6.6.1`.**
