### ISSUE TITLE
Something Wrong with Extractor

### ISSUE THREAD

**Issue by PenDZ-Alter** [Androz2091/discord-player#1736]
**Describe the bug**
When i play a song, it's turn the error and here's the error
```
Error: Could not extract stream for this track

evalmachine.<anonymous>:8
/,()[/,-71,//};Vla(ncode);
^

SyntaxError: Invalid regular expression: missing /
    at new Script (node:vm:100:7)
    at exports.decipherFormats (/home/runner/nahida-js/node_modules/ytdl-core/lib/sig.js:116:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at #throw (/home/runner/nahida-js/node_modules/discord-player/dist/index.js:1232:69)
    at GuildQueuePlayerNode.play (/home/runner/nahida-js/node_modules/discord-player/dist/index.js:1172:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (/home/runner/nahida-js/src/commands/music/play.js:61:34)
```

**To Reproduce**
Seems like something wrong with regex.
Maybe, you can fix this error

**Expected behavior**
Hopes everything back to normal :)

**Please complete the following information:**
 - Node Version: 18.12.1
 - Discord Player Version: 6.3.0
 - Discord.js Version: 14.11.0

**Comment by PenDZ-Alter** [comment]
Oh, sorry, 
okay just close it :)
