### ISSUE TITLE
(node:6201) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createMessageCollector' of undefined

### ISSUE THREAD

**Issue by WildZun** [Androz2091/discord-player#177]
Hello,
I have discordjs v12.5 and discord-player v3.0.3.

As soon as I launch the program and execute the play command, it gives me this error:
```
(node:6201) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createMessageCollector' of undefined
    at /home/pi/elementbot/node_modules/discord-player/src/Player.js:177:47
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here is my code:
```JS
const Discord = require("discord.js");
const fs = require("fs")
const { Player } = require("discord-player");
const db = require('quick.db')

module.exports.run = async (client, message, args, tools) => {

const prime = db.get(`${message.guild.id}_prime`)

  //Savoir si utilisateur est connecté dans un channel vocal
if(!message.member.voice.channel) return message.channel.send("<a:Cross:720531052031901726> Connectez-vous à un salon vocal !")
  else{
    //Si utilisateur a mis des arguments
    if(!args[0]) return message.channel.send("<a:Cross:720531052031901726> Mettez une URL YouTube/Spotify ou la musique que tu veux mettre ! Utilisation: `"+db.get(`${message.guild.id}_prefix`)+"play <URL YouTube/Mot clé>`")
    //Sinon il ajoute à la queue/joue de la musique
    else{
        let playing = client.player.isPlaying(message.guild.id);
        //Si le bot joue déjà 
        if(playing){
            //Ajouter de la musique à la queue
            let song = await client.player.addToQueue(message.guild.id, args.join(" "));
            if(!song) return message.channel.send("<a:Cross:720531052031901726> Je n'ai pas trouvé de musique avec ce nom")
          const play = new Discord.MessageEmbed()
            .setAuthor("✅ Ajouté à la queue !")
            .addField("Titre:", song.name, true)
            .addField("Auteur:", song.author, true)
            .addField("Durée:", song.duration, true)
            .setTimestamp()
            .setThumbnail(song.thumbnail)
            .setColor("0x#02AA11")
            .setFooter(`ElementBOT by WildZun - Play`, `https://cdn.glitch.com/68ce7727-e6b9-4983-a042-7b40c8297b75%2Flogo.png?v=1584196984007`)  
            message.channel.send(play);
        } else {
            //Sinon, jouer de la musique
            let song = await client.player.play(message.member.voice.channel, args.join(" "));
            if(!song) return message.channel.send("<a:Cross:720531052031901726> Je n'ai pas trouvé de musique avec ce nom")
        //Message de confirmation
          const play = new Discord.MessageEmbed()
            .setAuthor("✅ Je joue")
            .addField("Titre:", song.name, true)
            .addField("Auteur:", song.author, true)
            .addField("Durée:", song.duration, true)
            .setTimestamp()
            .setThumbnail(song.thumbnail)
            .setColor("0x#02AA11")
            .setFooter(`ElementBOT by WildZun - Play`, `https://cdn.glitch.com/68ce7727-e6b9-4983-a042-7b40c8297b75%2Flogo.png?v=1584196984007`) 
            message.channel.send(play);
             }
    }}
 
};

module.exports.help = {
  name: "play"
}
```

Please help me, I need help.
WildZun.

**Comment by udit2303** [comment]
Please update your code according to v3. The parameters have changed from `voice channel` to `message object` for `play`

**Comment by Androz2091** [comment]
Read the README file to get more details or join the [discord server](https://androz2091.fr/discord).
