### ISSUE TITLE
Randomly couldn't extract stream for tracks

### ISSUE THREAD

**Issue by Mylloon** [Androz2091/discord-player#1800]
**Describe the bug**

**To Reproduce**
1. Search for a music
2. The bot found it and join the voice call
3. The bot crash and leave the voice call

**Expected behavior**
The bot should play the song

**Please complete the following information:**
 - Node Version: 19.8.1
 - Discord Player Version: 6.6.2
 - Discord.js Version: 14.12.1

**Additional context**
Here is the error

```js
/app/node_modules/discord-player/dist/index.js:580
      const exception = new err.type(err.createError(...args));
                        ^


ERR_NO_RESULT: Could not extract stream for this track


TypeError: Cannot read properties of undefined (reading 'find')
    at video_basic_info (/app/node_modules/play-dl/dist/index.js:2:2210)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.video_info (/app/node_modules/play-dl/dist/index.js:3:1064)
    at async SpotifyExtractor._stream (/app/node_modules/@discord-player/extractor/dist/index.js:278:22)
    at async /app/node_modules/discord-player/dist/index.js:1896:12
    at async ExtractorExecutionContext.run (/app/node_modules/discord-player/dist/index.js:885:22)
    at async #createGenericStream (/app/node_modules/discord-player/dist/index.js:1890:22)
    at async GuildQueuePlayerNode.play (/app/node_modules/discord-player/dist/index.js:1794:9)
    at Proxy.<anonymous> (/app/node_modules/discord-player/dist/index.js:580:25)
    at #throw (/app/node_modules/discord-player/dist/index.js:1865:80)
    at GuildQueuePlayerNode.play (/app/node_modules/discord-player/dist/index.js:1810:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

If I wait 2-3min and retry, it works

**Comment by twlite** [comment]
@Mylloon hi sorry for late response. Can you try switching your youtube library? Seems to be `play-dl` issue.

**Comment by Mylloon** [comment]
Ok thanks for the info!

**Comment by Mylloon** [comment]
For info if someone have the same issues, `youtube-ext` isn't working either:

```js
/app/node_modules/discord-player/dist/index.js:580
      const exception = new err.type(err.createError(...args));
                        ^

ERR_NO_RESULT: Could not extract stream for this track

Error: Expected "formats" to be "object" but received "undefined".
    at /home/anri/Botanique/node_modules/youtube-ext/dist/generateStream.js:26:15
    at Generator.next (<anonymous>)
    at /home/anri/Botanique/node_modules/youtube-ext/dist/generateStream.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/anri/Botanique/node_modules/youtube-ext/dist/generateStream.js:4:12)
    at Object.getFormats (/home/anri/Botanique/node_modules/youtube-ext/dist/generateStream.js:23:47)
    at SpotifyExtractor._stream (/home/anri/Botanique/node_modules/@discord-player/extractor/dist/index.js:252:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/anri/Botanique/node_modules/discord-player/dist/index.js:1896:12
    at async ExtractorExecutionContext.run (/home/anri/Botanique/node_modules/discord-player/dist/index.js:885:22)
    at Proxy.<anonymous> (/home/anri/Botanique/node_modules/discord-player/dist/index.js:580:25)
    at #throw (/home/anri/Botanique/node_modules/discord-player/dist/index.js:1865:80)
    at GuildQueuePlayerNode.play (/home/anri/Botanique/node_modules/discord-player/dist/index.js:1810:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

`yt-stream` is working though

**Comment by twlite** [comment]
> For info if someone have the same issue, `youtube-ext` isn't working either:
> 
> ```js
> /app/node_modules/discord-player/dist/index.js:580
>       const exception = new err.type(err.createError(...args));
>                         ^
> 
> ERR_NO_RESULT: Could not extract stream for this track
> 
> Error: Expected "formats" to be "object" but received "undefined".
>     at /home/anri/Botanique/node_modules/youtube-ext/dist/generateStream.js:26:15
>     at Generator.next (<anonymous>)
>     at /home/anri/Botanique/node_modules/youtube-ext/dist/generateStream.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (/home/anri/Botanique/node_modules/youtube-ext/dist/generateStream.js:4:12)
>     at Object.getFormats (/home/anri/Botanique/node_modules/youtube-ext/dist/generateStream.js:23:47)
>     at SpotifyExtractor._stream (/home/anri/Botanique/node_modules/@discord-player/extractor/dist/index.js:252:40)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async /home/anri/Botanique/node_modules/discord-player/dist/index.js:1896:12
>     at async ExtractorExecutionContext.run (/home/anri/Botanique/node_modules/discord-player/dist/index.js:885:22)
>     at Proxy.<anonymous> (/home/anri/Botanique/node_modules/discord-player/dist/index.js:580:25)
>     at #throw (/home/anri/Botanique/node_modules/discord-player/dist/index.js:1865:80)
>     at GuildQueuePlayerNode.play (/home/anri/Botanique/node_modules/discord-player/dist/index.js:1810:56)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```
> 
> `yt-stream` is working though

looks like youtube-ext version does not match @discord-player/extractor version, could you update both of these to latest and also discord-player to latest?

**Comment by Mylloon** [comment]
yes sorry was exactly doing that, it is working perfectly with the latest version, thank you!
