### ISSUE TITLE
Player Error

### ISSUE THREAD

**Issue by Sobhan-SRZA** [Androz2091/discord-player#1928]
**Describe the bug**

**To Reproduce**
Full error message:
```
PlayerError: Failed to extract n-token decipher algorithm
    at Player.extractNSigSourceCode (/home/container/node_modules/youtubei.js/bundle/node.cjs:17843:13)
    at Player.<anonymous> (/home/container/node_modules/youtubei.js/bundle/node.cjs:17720:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/container/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
**Code Preview**
```js
const {
  Player
} = require("discord-player");
const { YoutubeiExtractor, generateOauthTokens } = require("discord-player-youtubei");
const player = new Player(client, {
  connectionTimeout: 5 * 60 * 1000 // 5 Minutes timeout for disconnect from voice.
});
(async () => {
  const oauthTokens = await generateOauthTokens(); // The tokens printed from step above
  await player.extractors.loadDefault((extractor) => extractor !== "YouTubeExtractor");
  await player.extractors.register(YoutubeiExtractor, {
      authentication: oauthTokens
  });
})();
```

**Please complete the following information:**
 - Node Version: 21.7.3
 - Discord Player Version: 6.7.0
 - Discord.js Version: 14.5.3

**Comment by Sobhan-SRZA** [comment]
I changed "discord-player" to 6.7.1 and "discord-player-youtubei" to 1.2.4 then it fixed.

**Comment by retrouser955** [comment]
Next time, please come open issues related to discord-player-youtubei on [here](https://github.com/retrouser955/discord-player-youtubei)
