### ISSUE TITLE
Cannot read 'id' of undefined

### ISSUE THREAD

**Issue by NewCoderOfDiscord** [Androz2091/discord-player#197]
This is what I get when I run my bot:

(node:341) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at /home/runner/MusicBotTest/node_modules/discord-player/src/Player.js:362:75
    at Map.find (/home/runner/MusicBotTest/node_modules/@discordjs/collection/dist/index.js:161:17)
    at Player.pause (/home/runner/MusicBotTest/node_modules/discord-player/src/Player.js:362:35)
    at Client.<anonymous> (/home/runner/MusicBotTest/index.js:32:21)
    at Client.emit (events.js:315:20)
    at Client.EventEmitter.emit (domain.js:483:12)
    at MessageCreateAction.handle (/home/runner/MusicBotTest/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/MusicBotTest/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/MusicBotTest/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/MusicBotTest/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
(node:341) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:341) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Androz2091** [comment]
@NewCoderOfDiscord we will need your code to help you. Please open a new issue with your code if you still have this problem
