### ISSUE TITLE
voice connection timeout

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [Androz2091/discord-player#219]
I'm getting this error when the bot is trying to join the voice channel, not sure where it's coming from

```bash
Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/ghostybot/node_modules/discord.js/src/client/voice/VoiceConnection.js:296:27)
    at /home/ghostybot/node_modules/discord.js/src/client/voice/VoiceConnection.js:324:61
    at Timeout.<anonymous> (/home/ghostybot/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
From previous event:
    at ClientVoiceManager.joinChannel (/home/ghostybot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:70:12)
    at VoiceChannel.join (/home/ghostybot/node_modules/discord.js/src/structures/VoiceChannel.js:134:30)
    at /home/ghostybot/node_modules/discord-player/src/Player.js:292:21
From previous event:
    at Player._createQueue (/home/ghostybot/node_modules/discord-player/src/Player.js:287:16)
    at Player.play (/home/ghostybot/node_modules/discord-player/src/Player.js:371:42) {
  [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT'
}
```

**Comment by Dev-CasperTheGhost** [comment]
Seems to be a me issue.

**Comment by Nat1001** [comment]
@Dev-CasperTheGhost I have the same issue, what was the problem?

**Comment by Dev-CasperTheGhost** [comment]
A rate limit if I remember correctly

**Comment by Nat1001** [comment]
How can I solve it ?

**Comment by Nat1001** [comment]
@Dev-CasperTheGhost sorry for ping but can you help me ?
