### ISSUE TITLE
[IMPORTANT] YouTube video links AND YouTube Playlist links are no longer working.

### ISSUE THREAD

**Issue by FS-Santi** [Androz2091/discord-player#224]
For playlist it throws this error: (node:4) UnhandledPromiseRejectionWarning: Error: Could not parse playist: Cannot read property 'shortBylineText' of undefined
2020-12-31T01:09:53.975801+00:00 app[Worker.1]:     at Function.getPlaylist (/app/node_modules/youtube-sr/src/main.js:59:19)
2020-12-31T01:09:53.975802+00:00 app[Worker.1]:     at runMicrotasks (<anonymous>)
2020-12-31T01:09:53.975803+00:00 app[Worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-31T01:09:53.975804+00:00 app[Worker.1]:     at async Player._handlePlaylist (/app/node_modules/discord-player/src/Player.js:314:26)
2020-12-31T01:09:53.975817+00:00 app[Worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).

-------------------------------------------------------------------------------------------------------------------------

FOR Video links it throws this error:  (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
2020-12-31T01:11:19.272547+00:00 app[Worker.1]:     at Player.play (/app/node_modules/discord-player/src/Player.js:351:69)
2020-12-31T01:11:19.272549+00:00 app[Worker.1]:     at runMicrotasks (<anonymous>)
2020-12-31T01:11:19.272549+00:00 app[Worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-31T01:11:19.272641+00:00 app[Worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).

**Comment by Androz2091** [comment]
@FS-Santi Are you still facing this problem?
