### ISSUE TITLE
Bot crashes when given a YouTube playlist link

### ISSUE THREAD

**Issue by EmirGuvenni** [Androz2091/discord-player#260]
I've tried a few playlist links and bot kept crashing when i gave [this link](https://www.youtube.com/playlist?list=PLr-d8g78zdF3ih686T3ZWOsLF5m-llb-5).

**Bot command:**
`$p https://www.youtube.com/playlist?list=PLr-d8g78zdF3ih686T3ZWOsLF5m-llb-5`
or
`$play https://www.youtube.com/playlist?list=PLr-d8g78zdF3ih686T3ZWOsLF5m-llb-5`

**Error message:** 
```
project/node_modules/youtube-sr/src/main.js:59
            throw new Error(`Could not parse playist: ${e.message || e}`);
                  ^
Error: Could not parse playist: Cannot read property 'shortBylineText' of undefined
    at Function.getPlaylist (/project/node_modules/youtube-sr/src/main.js:59:19)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at Player._handlePlaylist (/project/node_modules/discord-player/src/Player.js:316:26)
```

**My Code:**
```
export const run = async (client: Client, message: Message, args: string[]) => {
	let voiceChannel = message.member!.voice.channel;
	let arg = args.join(' ');

	if (voiceChannel?.full)
		return message.channel.send(
			Embed.error('Error', 'The voice channel you\'re in is full.')
		);

	if (!arg)
		return message.channel.send(
			Embed.error('Error 417', 'No search arguments provided.')
		);

	await player.play(message, arg, true);
}
```

**Comment by Androz2091** [comment]
@Snowflake107 it is fixed in latest youtube-sr right?

**Comment by Snowflake107** [comment]
Yeah, this should work on latest version 🤔

**Comment by EmirGuvenni** [comment]
Is there anything I could do on my side?

**Comment by Snowflake107** [comment]
@EmirGuvenni you can install `discord-player` via `npm i Snowflake107/discord-player#develop` or just wait for an update.

**Comment by EmirGuvenni** [comment]
I'll wait for an update. Keep up the great work.
