### ISSUE TITLE
Cannot read property 'end' of null (dispatcher)

### ISSUE THREAD

**Issue by BySantino12** [Androz2091/discord-player#263]
s!p 10 second video (me)

(bot):musical_note: - Escuchando ahora All over in 10 seconds en 「:computer:┊」Musica 2 ... (playing 10 seconds video)
(bot) :warning: - La musica termino y no hay mas en la lista ! (video end, and no more un queue)

s!p avicii waiting for love (me) (adding a music)

:musical_note: - Avicii - Waiting For Love Fue agregado a la lista ! (bot) (music added to te queue)

s!skip (me)

(bot not respose, and crash)

console error is this:

https://cdn.discordapp.com/attachments/805443933685415976/805619353244139570/20210131_230259.jpg

**Comment by BySantino12** [comment]
/home/container/node_modules/discord-player/src/Player.js:478
        queue.voiceConnection.dispatcher.end()
                                         ^

TypeError: Cannot read property 'end' of null
    at Player.skip (/home/container/node_modules/discord-player/src/Player.js:478:42)
    at Object.execute (/home/container/commands/music/skip.js:14:23)
    at module.exports (/home/container/events/message.js:13:18)
    at Client.emit (node:events:379:20)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:132:16)

**Comment by Androz2091** [comment]
This should now be fixed in develop

**Comment by Androz2091** [comment]
Hello :wave:
Thank you for reporting this issue. It has been fixed in [v3.3.1](https://github.com/Androz2091/discord-player/releases/tag/v3.3.1).
