### ISSUE TITLE
TypeError: Expected a number. Happens on queue createProgressBar

### ISSUE THREAD

**Issue by jameslinimk** [Androz2091/discord-player#285]
```js
TypeError: Expected a number
    at module.exports (/pro/burito/node_modules/parse-ms/index.js:4:9)
    at Player.createProgressBar (/pro/burito/node_modules/discord-player/src/Player.js:1036:60)
    at /pro/burito/commands/music/queue.js:45:83
    at Array.forEach (<anonymous>)
    at Object.execute (/pro/burito/commands/music/queue.js:37:13)
    at Client.<anonymous> (/pro/burito/index.js:740:11)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/pro/burito/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/pro/burito/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/pro/burito/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
```

**Comment by Androz2091** [comment]
What are you playing? (the URL of the youtube song would be helpful for example)

**Comment by Androz2091** [comment]
Never mind, I can reproduce the bug. Thank you
