### ISSUE TITLE
Unhandled error.

### ISSUE THREAD

**Issue by FSCYT** [Androz2091/discord-player#287]
This is an error I always get, I can't seem to find where the issue is.
```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('NotPlaying')
    at Player.emit (events.js:304:17)
    at Player.nowPlaying (/home/mido/Coding/Javascript/cyber-2.0/Testing-Bot/node_modules/discord-player/src/Player.js:509:33)
    at PlayCommand.run (/home/mido/Coding/Javascript/cyber-2.0/Testing-Bot/src/commands/Music/PlayCommand.js:36:31)
    at MessageEvent.run (/home/mido/Coding/Javascript/cyber-2.0/Testing-Bot/src/events/message/MessageEvent.js:91:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'NotPlaying'
}
```
PlayCommand.js:36:31 `const song = client.player.nowPlaying(message);`

**Comment by FSCYT** [comment]
There weren't any songs playing thats why this error appeared!
