### ISSUE TITLE
Error when starting the bot

### ISSUE THREAD

**Issue by JustReddy7397** [Androz2091/discord-player#296]
/home/container/node_modules/youtube-sr/build/Util.js:262
        const author = playlistDetails[1]?.playlistSidebarSecondaryInfoRenderer.videoOwner;
                                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/container/node_modules/youtube-sr/build/main.js:7:32)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/container/node_modules/discord-player/src/Player.js:3:14)
    
    
    
    
    very strange :c
    
    This is not the only error tho, when i fix that, it throws another one

**Comment by Snowflake107** [comment]
hey, use node.js `v14.x`

**Comment by JustReddy7397** [comment]
> hey, use node.js `v14.x` or higher

Worked Thanks
