### ISSUE TITLE
Issue: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by advitrocks9** [Androz2091/discord-player#297]
Error: 
const author = playlistDetails[1]?.playlistSidebarSecondaryInfoRenderer.videoOwner;
                                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Downloads\Vibes\node_modules\youtube-sr\build\main.js:7:32)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

**Comment by Snowflake107** [comment]
see #296 @advitrocks9

**Comment by SkyDonald** [comment]
You must use node v14.x or highter

**Comment by advitrocks9** [comment]
i was using node v12

**Comment by Snowflake107** [comment]
@advitrocks9 install node.js v14 and then run your code :)

**Comment by advitrocks9** [comment]
It worked thanks
