### ISSUE TITLE
YouTube playlists?

### ISSUE THREAD

**Issue by Spencer-0003** [Androz2091/discord-player#300]
I've noticed that when adding a YouTube playlist it only plays the first song, not sure if this is intended or not but it would nice to play all songs from the playlist.

**Comment by Androz2091** [comment]
Hello, I will try to reproduce this bug

**Comment by Spencer-0003** [comment]
Not sure if it matters but the person who reported this bug to me said they was trying to play this playlist: https://www.youtube.com/playlist?list=PL3hOfniudRzvAUIYCkLv5dMNBMHznUZ6Z

**Comment by jameslinimk** [comment]
> Not sure if it matters but the person who reported this bug to me said they was trying to play this playlist: https://www.youtube.com/playlist?list=PL3hOfniudRzvAUIYCkLv5dMNBMHznUZ6Z

Works for me. What is your current discord-player version?

**Comment by Spencer-0003** [comment]
> 
> 
> > Not sure if it matters but the person who reported this bug to me said they was trying to play this playlist: https://www.youtube.com/playlist?list=PL3hOfniudRzvAUIYCkLv5dMNBMHznUZ6Z
> 
> Works for me. What is your current discord-player version?

3.3.2

**Comment by hands8142** [comment]
All the songs on the playlist play well.

**Comment by Spencer-0003** [comment]
It adds all the songs to the queue but after the first one finishes playing, it doesn't start another (only happening with YouTube playlists for some reason).

**Comment by Androz2091** [comment]
It works for me:
![Capture d’écran 2021-02-26 à 13 39 35](https://user-images.githubusercontent.com/42497995/109301321-16be3d00-7838-11eb-99cc-6b4038ddb1df.png)

**Comment by Androz2091** [comment]
I'm using this bot: https://github.com/ZerioDev/Music-bot
Can you try with this one?

**Comment by Spencer-0003** [comment]
> 
> 
> I'm using this bot: https://github.com/ZerioDev/Music-bot
> Can you try with this one?

Did some testing and got my bot to throw an error

```
Error: Video unavailable
    at Object.exports.playError (/app/node_modules/ytdl-core/lib/utils.js:124:12)
    at downloadFromInfoCallback (/app/node_modules/ytdl-core/lib/index.js:72:19)
    at /app/node_modules/ytdl-core/lib/index.js:20:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Emitted 'error' event on Encoder instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)```

**Comment by Androz2091** [comment]
Hm. If you're using the latest discord-player version, it should not throw this error

**Comment by onekin1225** [comment]
i got this error 

\node_modules\youtube-sr\build\main.js:69
                                    url: item.channel.thumbnails?.default.url,

**Comment by Snowflake107** [comment]
@onekin1225 are you using node.js v14?

**Comment by onekin1225** [comment]
i changed
bcz i saw docs

**Comment by Spencer-0003** [comment]
> 
> 
> Hm. If you're using the latest discord-player version, it should not throw this error

I'm using discord-player v3.3.2 and NodeJS v15
