### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by alima566** [Androz2091/discord-player#310]
I keep getting this error and it's causing my bot to not start at all.

```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/bot/node_modules/discord-player/src/Player.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/bot/node_modules/discord-player/src/Player.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:74:18)
/root/bot/node_modules/discord-player/node_modules/youtube-sr/build/main.js:69
                                    url: item.channel.thumbnails?.default.url,
                                                                 ^
```

**Comment by alima566** [comment]
Never mind, I have figured out what the issue for this was, however, this brings up another issue. After selecting a song to play from the menu, the bot will join the VC, but will immediately leave the VC and says that there is no more music playing.

**Comment by Androz2091** [comment]
Do you have any error in the terminal?

**Comment by ToledoSDL** [comment]
![image](https://user-images.githubusercontent.com/65132614/109417116-feb5fd00-79a0-11eb-99f6-c58cbf2cf3c3.png)
i think this will resolve

**Comment by alima566** [comment]
Hi, sorry I have discovered what was causing this and have fixed it myself. It was nothing related to your package. Apologies for the inconvenience.

**Comment by felarck** [comment]
I got the same syntax error, but I don't know how to fix it. Can you please tell me the solution?

**Comment by alima566** [comment]
You need to update to node v14

**Comment by felarck** [comment]
Ok, thanks!
