### ISSUE TITLE
Cannot run a bot with discord-player installed.

### ISSUE THREAD

**Issue by iceyym8** [Androz2091/discord-player#320]
When running my bot, I get the error below, cannot even start the bot.

                            views: (typeof item.views === "number" || item.views || 0) ?? 0
                                                                                        ^  

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\USER\Desktop\Comet\node_modules\discord-player\src\Player.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\USER\Desktop\Comet\node_modules\discord-player\index.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

**Comment by iceyym8** [comment]
Fixed, was using node v12 instead of v14, the update seemed to help,
