### ISSUE TITLE
[BUG] lyrics

### ISSUE THREAD

**Issue by hands8142** [Androz2091/discord-player#420]
**Describe the bug**
Occurred while using lyrics using @discord-player/extractor.

**To Reproduce**
Occurs when you attempt to import and use @discord-player/extractor in a typescript.

**Please complete the following information:**
 - Node Version: 16.1.0
 - Discord Player Version: 4.0.7
 - Discord.js Version: 12.5.3

**Comment by hands8142** [comment]
`/Users/handongsu/Documents/js/geugeo/node_modules/discord-player/lib/Player.js:844
            const data = yield extractor.Lyrics(query);
                                         ^
TypeError: extractor.Lyrics is not a function
    at Player.<anonymous> (/Users/handongsu/Documents/js/geugeo/node_modules/discord-player/lib/Player.js:844:42)
    at Generator.next (<anonymous>)
    at /Users/handongsu/Documents/js/geugeo/node_modules/discord-player/lib/Player.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/handongsu/Documents/js/geugeo/node_modules/discord-player/lib/Player.js:4:12)
    at Player.lyrics (/Users/handongsu/Documents/js/geugeo/node_modules/discord-player/lib/Player.js:840:16)
    at BackCommand.<anonymous> (/Users/handongsu/Documents/js/geugeo/src/commands/music/LyricsCommand.ts:11:44)
    at Generator.next (<anonymous>)
    at /Users/handongsu/Documents/js/geugeo/src/commands/music/LyricsCommand.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/handongsu/Documents/js/geugeo/src/commands/music/LyricsCommand.ts:4:12)
    at BackCommand.run (/Users/handongsu/Documents/js/geugeo/src/commands/music/LyricsCommand.ts:21:16)
    at /Users/handongsu/Documents/js/geugeo/src/events/message/MessageEvent.ts:41:19
    at Array.map (<anonymous>)
    at MessageEvent.<anonymous> (/Users/handongsu/Documents/js/geugeo/src/events/message/MessageEvent.ts:28:19)
    at Generator.next (<anonymous>)`

**Comment by hands8142** [comment]
/Users/handongsu/Documents/js/geugeo/node_modules/discord-player/lib/Player.js:844
            const data = yield extractor.Lyrics(query);
                                         ^
TypeError: extractor.Lyrics is not a function
    at Player.<anonymous> (/Users/handongsu/Documents/js/geugeo/node_modules/discord-player/lib/Player.js:844:42)
    at Generator.next (<anonymous>)
    at /Users/handongsu/Documents/js/geugeo/node_modules/discord-player/lib/Player.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/handongsu/Documents/js/geugeo/node_modules/discord-player/lib/Player.js:4:12)
    at Player.lyrics (/Users/handongsu/Documents/js/geugeo/node_modules/discord-player/lib/Player.js:840:16)
    at BackCommand.<anonymous> (/Users/handongsu/Documents/js/geugeo/src/commands/music/LyricsCommand.ts:11:44)
    at Generator.next (<anonymous>)
    at /Users/handongsu/Documents/js/geugeo/src/commands/music/LyricsCommand.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/handongsu/Documents/js/geugeo/src/commands/music/LyricsCommand.ts:4:12)
    at BackCommand.run (/Users/handongsu/Documents/js/geugeo/src/commands/music/LyricsCommand.ts:21:16)
    at /Users/handongsu/Documents/js/geugeo/src/events/message/MessageEvent.ts:41:19
    at Array.map (<anonymous>)
    at MessageEvent.<anonymous> (/Users/handongsu/Documents/js/geugeo/src/events/message/MessageEvent.ts:28:19)
    at Generator.next (<anonymous>)

**Comment by hands8142** [comment]
import { Player } from 'discord-player';
import { Reverbnation } from "@discord-player/extractor";
const player = new Player(client);
player.use("reverbnation", Reverbnation);

const lyrics = await client.player.lyrics(args.join(" "));
message.channel.send(lyrics.lyrics ? lyrics.lyrics : "자막을 찾을 수 없습니다.");

**Comment by Snowflake107** [comment]
This is because there was a new update to `@discord-player/extractor` and the current `discord-player`'s code is using the older version. You can downgrade the `@discord-player/extractor` and it should work

**Comment by hands8142** [comment]
Older versions of @discord-player/extractor do not support typescript.

**Comment by Snowflake107** [comment]
You dont need typescript to use `@discord-player/extractor` because discord player handles it by default for you. You just have to install it and that's it

**Comment by hands8142** [comment]
Okay, let me know if you have any updates that support the latest @discord-player/extractor.

**Comment by RMFireSteel** [comment]
Hello World !
For my part I had exactly the same problem that I was able to fix a previous version of @discord-plyaer/extractor -> 2.0.2. However a problem persists and annoys me strongly. For each music I want to look for the same error message appears, for Example here with Van Halen - Jump :

![error](https://user-images.githubusercontent.com/66364083/119322316-cf501d00-bc7d-11eb-98bf-ac00f1d9b426.JPG)

and this is my code :
```js
let query = `${artist} ${songName}`;
console.log(query);

const lyrics = await client.player.lyrics(query)
message.channel.send(lyrics.lyrics);
```

Can anyone help me :,-) ?
