### ISSUE TITLE
[QUESTION] J’ai une erreur mais je ne comprend pas d’ou elle viens…

### ISSUE THREAD

**Issue by VinxVinx** [Androz2091/discord-player#438]
**Question**
J’ai récemment écouté de la musique avec mon bot et il me sort l’erreur suivante:

```
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at PassThrough.ondata (internal/streams/readable.js:745:22)
    at PassThrough.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
Emitted 'error' event on Player instance at:
    at Encoder.<anonymous> (/moon/node_modules/discord-player/lib/Player.js:1234:30)
    at Encoder.emit (events.js:388:22)
    at FFmpeg.<anonymous> (/moon/node_modules/discord-ytdl-core/index.js:1:1327)
    at FFmpeg.emit (events.js:388:22)
    at Socket.processError (/moon/node_modules/prism-media/src/core/FFmpeg.js:65:40)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}```

D’ou viens t-elle?
Cordialement

**Comment by Snowflake107** [comment]
#378
