### ISSUE TITLE
[QUESTION] Error when i do play command

### ISSUE THREAD

**Issue by VinxVinx** [Androz2091/discord-player#473]
**Question**

When i do the play command, my bot join the voice channel but it don’t starting music and he logs this error:

```js
(node:13295) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('MusicStarting')
    at Player.emit (events.js:365:17)
    at Player.stop (/moon/node_modules/discord-player/lib/Player.js:681:18)
    at Object.exports.run (/moon/commands/Musique/stop.js:16:24)
    at Query.onResult (/moon/events/message.js:316:32)
    at /moon/node_modules/mysql2/lib/commands/query.js:72:16
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13295) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
```

How can i do ?

**Comment by Snowflake107** [comment]
Looks like voice connection was not created or something else interrupted the voice connection.
