### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by L0SER8228** [Androz2091/discord-player#476]
**Describe the bug**

TypeError: Cannot read property 'simpleText' of undefined
    at Function.getPlaylist (/app/node_modules/youtube-sr/build/Util.js:255:44)
    at Function.<anonymous> (/app/node_modules/youtube-sr/build/main.js:81:35)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/youtube-sr/build/main.js:9:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
**To Reproduce**

**Expected behavior**

It should play the playlist without any error.
**Screenshots**

**Please complete the following information:**
 - Node Version: [14.x]
 - Discord Player Version: [12.5.3]
 - Discord.js Version: [4.1.0]

**Additional context**

I tried to play the following playlist
https://youtube.com/playlist?list=RDCLAK5uy_ksEjgm3H_7zOJ_RHzRjN1wY-_FFcs7aAU

**Comment by u-sayuri** [comment]
that's a problem within `youtube-sr` package that didn't handle the data properly. might have to wait for a fix or you can just modify the source code :)

**Comment by Snowflake107** [comment]
fixed this in youtube-sr
