### ISSUE TITLE
Error: Status code: 416 - ytdl

### ISSUE THREAD

**Issue by iquantime** [Androz2091/discord-player#49]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Status code: 416
    at ClientRequest.<anonymous> (/Users/user/Documents/project/node_modules/miniget/dist/index.js:156:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)

To solve this just add `highWaterMark` in `node_modules/discord-player/src/Player.js`

`const newStream = ytdl(queue.playing.url, {
                filter: 'audioonly',
                opusEncoded: true,
                encoderArgs,
                seek: seekTime / 1000,
                highWaterMark: 1<<25
            })
`

maybe could add `highWaterMark` option in the `PlayerOptions`?

**Comment by Snowflake107** [comment]
@iquantime already added. You can check **[this](https://github.com/Androz2091/discord-player/commit/af8dac51f436b69180d6b24b7ec6fe8b3e39fa70#diff-57dfd10e73b05f2ac7dda337ab53d555)**

**Comment by Androz2091** [comment]
Yes, it should be fixed in v2.2.0.
