### ISSUE TITLE
what happen /

### ISSUE THREAD

**Issue by Kimtav** [Androz2091/discord-player#560]
Uncaught Promise Error:  TypeError: channel.join is not a function
    at C:\Users\PC GAMER\Desktop\Assly v2\node_modules\discord-player\lib\Player.js:1033:18
    at new Promise (<anonymous>)
    at Player._createQueue (C:\Users\PC GAMER\Desktop\Assly v2\node_modules\discord-player\lib\Player.js:1025:16)
    at Player.<anonymous> (C:\Users\PC GAMER\Desktop\Assly v2\node_modules\discord-player\lib\Player.js:477:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\PC GAMER\Desktop\Assly v2\node_modules\discord-player\lib\Player.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by Snowflake107** [comment]
You cannot use discord-player v4.x.x with discord.js v13.
