### ISSUE TITLE
Error: write EPIPE when trying to enable filters

### ISSUE THREAD

**Issue by blaise69** [Androz2091/discord-player#58]
```
events.js:173
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at FFmpeg.onerror (_stream_readable.js:720:7)
    at FFmpeg.emit (events.js:196:13)
    at Socket.processError (/rbd/pnpm-volume/5c18d4c9-69ed-4098-87d9-f87cf4c5fc9d/node_modules/.registry.npmjs.org/prism-media/1.2.2/node_modules/prism-media/src/core/FFmpeg.js:64:40)
    at Socket.emit (events.js:196:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:438:5)
    at onwrite (_stream_writable.js:459:5)
    at internal/streams/destroy.js:49:7
    at Socket._destroy (net.js:593:3)
```
That is the terminal when i try to enable a filter

**Comment by Snowflake107** [comment]
@blaise69 your FFmpeg doesn't support some filters (try updating)

**Comment by blaise69** [comment]
Okay sweet thanks!

**Comment by blaise69** [comment]
Yup it worked!!!!
