### ISSUE TITLE
Cannot use destroyed queue

### ISSUE THREAD

**Issue by DemonixDev** [Androz2091/discord-player#648]
**Describe the bug**
I remaked your example and when i try to do play i get error 
`/home/container/node_modules/discord-player/lib/Structures/Queue.js:715
throw new Error("Cannot use destroyed queue");
^
Error: Cannot use destroyed queue
at Queue._Queue_watchDestroyed (/home/container/node_modules/discord-player/lib/Structures/Queue.js:715:15)
at Queue.addTrack (/home/container/node_modules/discord-player/lib/Structures/Queue.js:233:84)
at Object.execute (/home/container/commands/Music/play.js:41:78)
at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Expected behavior**
Start play music

**Please complete the following information:**
 - Node Version: v14
 - Discord Player Version: lastest dev
 - Discord.js Version: lastest dev

**Comment by DevAndromeda** [comment]
do not open issues for dev version, you can either create a new **[discussion](https://github.com/Androz2091/discord-player/discussions)** or comment on #515
