### ISSUE TITLE
Status code: 403 (version 4.1.4)

### ISSUE THREAD

**Issue by LucasPanais** [Androz2091/discord-player#695]
MinigetError: Status code: 403
    at ClientRequest.<anonymous> (/home/pi/panais/node_modules/miniget/dist/index.js:210:27)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  statusCode: 403
}

**Comment by DevAndromeda** [comment]
Hello, we no longer support v4.1.4, you should move to v5.x.x

**Comment by LucasPanais** [comment]
I do, but I noticed there were a lot of big changes that I don’t have time to do especially for a while
