### ISSUE TITLE
"[DestroyedQueue] Cannot use destroyed queue" after calling stop() with songs in queue

### ISSUE THREAD

**Issue by joshuayuen99** [Androz2091/discord-player#734]
**Describe the bug**
The following `connectionError` event fires within ~0.5 seconds after calling stop() with a song playing and at least 1 song in the queue afterwards. The bot correctly stops playing music and leaves the voice channel:
```
DestroyedQueue: [DestroyedQueue] Cannot use destroyed queue
    at new PlayerError (E:\TundraBot\node_modules\discord-player\dist\Structures\PlayerError.js:28:15)
    at Queue._Queue_watchDestroyed (E:\TundraBot\node_modules\discord-player\dist\Structures\Queue.js:754:45)
    at Queue.setVolume (E:\TundraBot\node_modules\discord-player\dist\Structures\Queue.js:308:88)
    at Queue.<anonymous> (E:\TundraBot\node_modules\discord-player\dist\Structures\Queue.js:673:18)
    at Generator.next (<anonymous>)
    at fulfilled (E:\TundraBot\node_modules\discord-player\dist\Structures\Queue.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**
1) start playing a song
2) add another song to the queue
3) call stop()
4) get the above error

**Expected behavior**
Stop without errors.

**Please complete the following information:**
 - Node Version: 16.6.1
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.1.0

**Comment by 3061LRTAGSPKJMORMRT** [comment]
i get the same error as well

**Comment by Stive99** [comment]
I have the same

**Comment by ethhaqn** [comment]
I get the same error. Not sure what triggers it for me but it just sometimes randomly appears. As far as I am aware the error doesn't break anything or cause anything abnormal to occur.

**Comment by SuperSweatyTejas** [comment]
same aswell

**Comment by SuperSweatyTejas** [comment]
any fixes?

**Comment by pauldb09** [comment]
I got same error but it does not crash the bot

**Comment by DevAndromeda** [comment]
Looks like you are somehow calling `stop()` multiple times after the queue is destroyed. You can do something like:

```js
if (queue.destroyed) return console.log("Cannot go further because the queue is destroyed");
```
