### ISSUE TITLE
Error: spawn ENOMEM

### ISSUE THREAD

**Issue by thanhgaming5550** [Androz2091/discord-player#811]
**Describe the bug**
Error: spawn ENOMEM when play a song

**To Reproduce**
Ask the bot to play a song

**Expected behavior**
Bot play songs

**Screenshots**
![image](https://user-images.githubusercontent.com/62001770/134811200-1295d4c3-f3b6-48b4-883c-b442a1d3a85a.png)

**Please complete the following information:**
 - Node Version: 16.10.0
 - Discord Player Version: 5.0.2
 - Discord.js Version: 13.0.1

**Additional context**
Logs Console : 
```
thanhgaming5550#xxxx : />play never
Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at Function.create (/workspace/node_modules/prism-media/src/core/FFmpeg.js:156:25)
    at new FFmpeg (/workspace/node_modules/prism-media/src/core/FFmpeg.js:45:27)
    at Object.StreamDownloader [as default] (/workspace/node_modules/discord-ytdl-core/index.js:1:833)
    at Queue.<anonymous> (/workspace/node_modules/discord-player/dist/Structures/Queue.js:645:53)
    at Generator.next (<anonymous>)
    at /workspace/node_modules/discord-player/dist/Structures/Queue.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/node_modules/discord-player/dist/Structures/Queue.js:4:12) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}

thanhgaming5550#xxxx : />play Never gonna
Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at Function.create (/workspace/node_modules/prism-media/src/core/FFmpeg.js:156:25)
    at new FFmpeg (/workspace/node_modules/prism-media/src/core/FFmpeg.js:45:27)
    at Object.StreamDownloader [as default] (/workspace/node_modules/discord-ytdl-core/index.js:1:833)
    at Queue.<anonymous> (/workspace/node_modules/discord-player/dist/Structures/Queue.js:645:53)
    at Generator.next (<anonymous>)
    at /workspace/node_modules/discord-player/dist/Structures/Queue.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/node_modules/discord-player/dist/Structures/Queue.js:4:12) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}
thanhgaming5550#xxxx : />play Hi
Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at Function.create (/workspace/node_modules/prism-media/src/core/FFmpeg.js:156:25)
    at new FFmpeg (/workspace/node_modules/prism-media/src/core/FFmpeg.js:45:27)
    at Object.StreamDownloader [as default] (/workspace/node_modules/discord-ytdl-core/index.js:1:833)
    at Queue.<anonymous> (/workspace/node_modules/discord-player/dist/Structures/Queue.js:645:53)
    at Generator.next (<anonymous>)
    at /workspace/node_modules/discord-player/dist/Structures/Queue.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/node_modules/discord-player/dist/Structures/Queue.js:4:12) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}
```
**The bot entered the said channel but did not play the music. I think this is due to FFmpeg.**

**Comment by DevAndromeda** [comment]
You should allocate more memory while starting your bot. By default, node allocates 512MB mem and that error means you ran out of memory.

For example, if your system has more than 512MB memory, you can do something like `node ----max-old-space-size=1024 myfile.js` which would allocate 1GB memory

**Comment by thanhgaming5550** [comment]
> You should allocate more memory while starting your bot. By default, node allocates 512MB mem and that error means you ran out of memory.
> 
> For example, if your system has more than 512MB memory, you can do something like `node ----max-old-space-size=1024 myfile.js` which would allocate 1GB memory

return error : `bad option: ----max-old-space-size=1024`
