### ISSUE TITLE
Broken discord-player dependencies instalation

### ISSUE THREAD

**Issue by Ninja2Gods** [Androz2091/discord-player#825]
When I install discord-player with npm, the dependencies can't install with it and shows this error

`Error: Error: Cannot find module '@discordjs/opus'
Require stack:
- /home/container/node_modules/prism-media/src/util/loader.js
- /home/container/node_modules/prism-media/src/opus/Opus.js
- /home/container/node_modules/prism-media/src/opus/index.js
- /home/container/node_modules/prism-media/src/index.js
- /home/container/node_modules/discord-ytdl-core/index.js
- /home/container/node_modules/discord-player/dist/Structures/Queue.js
- /home/container/node_modules/discord-player/dist/Player.js
- /home/container/node_modules/discord-player/dist/index.js
- /home/container/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/container/node_modules/prism-media/src/util/loader.js
- /home/container/node_modules/prism-media/src/opus/Opus.js
- /home/container/node_modules/prism-media/src/opus/index.js
- /home/container/node_modules/prism-media/src/index.js
- /home/container/node_modules/discord-ytdl-core/index.js
- /home/container/node_modules/discord-player/dist/Structures/Queue.js
- /home/container/node_modules/discord-player/dist/Player.js
- /home/container/node_modules/discord-player/dist/index.js
- /home/container/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/container/node_modules/prism-media/src/util/loader.js
- /home/container/node_modules/prism-media/src/opus/Opus.js
- /home/container/node_modules/prism-media/src/opus/index.js
- /home/container/node_modules/prism-media/src/index.js
- /home/container/node_modules/discord-ytdl-core/index.js
- /home/container/node_modules/discord-player/dist/Structures/Queue.js
- /home/container/node_modules/discord-player/dist/Player.js
- /home/container/node_modules/discord-player/dist/index.js
- /home/container/index.js
    at Object.loader [as require] (/home/container/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/container/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/container/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/home/container/node_modules/prism-media/src/opus/Opus.js:149:5)
    at Object.transformer (/home/container/node_modules/@discordjs/voice/dist/audio/TransformerGraph.js:120:24)
    at /home/container/node_modules/@discordjs/voice/dist/audio/AudioResource.js:156:60
    at Array.map (<anonymous>)
    at Object.createAudioResource (/home/container/node_modules/@discordjs/voice/dist/audio/AudioResource.js:156:41)
    at StreamDispatcher.createStream (/home/container/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:108:38)
    at Queue.<anonymous> (/home/container/node_modules/discord-player/dist/Structures/Queue.js:666:46)`

**Comment by DevAndromeda** [comment]
remove your lockfile (`package-lock.json`/`yarn.lock`) and `node_modules` and run `npm install`

**Comment by DevAndromeda** [comment]
stale
