### ISSUE TITLE
Channel type must be GUILD_VOICE or GUILD_STAGE_VOICE, got voice!

### ISSUE THREAD

**Issue by Arburich** [Androz2091/discord-player#855]
InvalidArgType: [InvalidArgType] Channel type must be GUILD_VOICE or GUILD_STAGE_VOICE, got voice!
    at new PlayerError (C:\Users\Luna\Desktop\Luna\node_modules\discord-player\dist\Structures\PlayerError.js:28:15)
    at Queue.<anonymous> (C:\Users\Luna\Desktop\Luna\node_modules\discord-player\dist\Structures\Queue.js:160:23)
    at Generator.next (<anonymous>)
    at C:\Users\Luna\Desktop\Luna\node_modules\discord-player\dist\Structures\Queue.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Luna\Desktop\Luna\node_modules\discord-player\dist\Structures\Queue.js:4:12)
    at Queue.connect (C:\Users\Luna\Desktop\Luna\node_modules\discord-player\dist\Structures\Queue.js:155:16)
    at Object.exports.run (C:\Users\Luna\Desktop\Luna\commands\play.js:19:48) {
  createdAt: 2021-10-20T05:48:50.213Z,
  statusCode: 'InvalidArgType'
}

The Line in play.js:
`if (!queue.connection) await queue.connect(message.member.voice.channel);`

Bot is expected to play on: 

`!play https://www.youtube.com/watch?v=dQw4w9WgXcQ`, the following video. 

Bot has:
- Sufficient permissions to enter said channel. 
- Server is community enabled, meaning it has access to newer stages and whatnot. 
- Created a new VC just in case the old VCs were somehow affecting it

 - Node Version: 17.0.0
 - Discord Player Version: 5.1.0
 - Discord.js Version: 13.2.0
 
 Bot with basic music implementation here: https://github.com/arburich/luna 
 (play.js is the only command that has this music stuff so far)
 
Music player stuff was taken from https://github.com/ZerioDev/Music-bot

**Comment by DevAndromeda** [comment]
we no longer support discord.js v12, please use discord.js v13 or use the old version of this library
