### ISSUE TITLE
DestroyedQueue: [DestroyedQueue] Cannot use destroyed queue

### ISSUE THREAD

**Issue by SuperSweatyTejas** [Androz2091/discord-player#874]
Getting

DestroyedQueue: [DestroyedQueue] Cannot use destroyed queue
    at new PlayerError (/home/container/node_modules/discord-player/dist/Structures/PlayerError.js:28:15)
    at Queue._Queue_watchDestroyed (/home/container/node_modules/discord-player/dist/Structures/Queue.js:796:45)
    at Queue.setVolume (/home/container/node_modules/discord-player/dist/Structures/Queue.js:335:88)
    at Queue.<anonymous> (/home/container/node_modules/discord-player/dist/Structures/Queue.js:713:18)
    at Generator.next (<anonymous>)
    at fulfilled (/home/container/node_modules/discord-player/dist/Structures/Queue.js:11:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    
    
**Please complete the following information:**
 - Node Version: v16.1.0
 - Discord Player Version: 5.1.0
 - Discord.js Version: latest

**Comment by DevAndromeda** [comment]
#734
