### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by battincik** [Androz2091/discord-player#948]
I couldn't figure out why exactly, but I think there is a problem with spotify playlists.

**"discord-player": "^5.2.0",**

Console output:

```
\node_modules\discord-player\dist\Player.js:385
                                title: (_a = m.track.name) !== null && _a !== void 0 ? _a : "",
                                                     ^
TypeError: Cannot read properties of null (reading 'name')
    at \node_modules\discord-player\dist\Player.js:385:54
    at Array.map (<anonymous>)
    at Player.<anonymous> (\node_modules\discord-player\dist\Player.js:382:72)
    at Generator.next (<anonymous>)
    at fulfilled (\node_modules\tslib\tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Grayson-code** [comment]
Having same issue but this time with track.artists

**Comment by DevAndromeda** [comment]
re-open if this still persists
