### ISSUE TITLE
TypeError: privateMap.get is not a function in discord-player@5.2.0^

### ISSUE THREAD

**Issue by GaryCraft** [Androz2091/discord-player#981]
**Describe the bug**
Queue.addTracks()
and
Queue.addTrack()
Do not work

**To Reproduce**
Create a project
Install discord-player library as Normal
Use methods described above
Run

**Expected behavior**
Tracks get added to the Queue and the corresponding event gets emitted

**Resulting Behaviour**
Error gets Thrown
```ts
TypeError: privateMap.get is not a function
    at __classPrivateFieldGet (--\git\BOT\node_modules\tslib\tslib.js:250:27)
    at Queue.addTrack (--\git\BOT\node_modules\discord-player\dist\Structures\Queue.js:237:48)
    at Object.<anonymous> (--\git\BOT\src\interactions\Music\play.js:87:28)
    at Generator.throw (<anonymous>)
    at rejected (G:\pro--\git\BOT\src\interactions\Music\play.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/68017132/148841819-b27cb206-dea3-40ca-a673-5346ef407565.png)

**Please complete the following information:**
 - Node Version: v16.13.0
 - Discord Player Version: 5.2.0
 - Discord.js Version: 13.5.1

**Additional context**

Just Updated the Bot both to TypeScript and a new Version of discord-player

**Comment by GaryCraft** [comment]
This Error does not occur on Version 5.1.0 of discord-player

**Comment by DevAndromeda** [comment]
re-open if this still persists
