### ISSUE TITLE
Bug VoiceConnection

### ISSUE THREAD

**Issue by LeRomino** [Androz2091/discord-player#996]
} Error: Cannot destroy VoiceConnection - it has already been destroyed
    at K.destroy (/home/container/node_modules/@discordjs/voice/dist/index.js:8:10744)
    at StreamDispatcher.<anonymous> (/home/container/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:48:50)
    at Generator.throw (<anonymous>)
    at rejected (/home/container/node_modules/tslib/tslib.js:115:69)
(node:27) Warning: [DiscordPlayerWarning] Unhandled "connectionError" event! Events "error", "connectionError" must have event listeners!
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by pauldb09** [comment]
#993

**Comment by LeRomino** [comment]
I don't understand, how can I fix the error @pauldb09
